version: 0.2
phases:
  install:
    commands:
      - echo install step...
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --short --client
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - echo Logging into Amazon EKS...
      - aws eks --region us-west-2 update-kubeconfig --name group1-eks-cluster
      - echo check config
      - kubectl config view --minify
      - echo check kubectl access
      - kubectl get svc
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t group1:latest .
      - docker tag group1:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/akash-capstone2-testrepo:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo  push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/akash-capstone2-testrepo:latest
      - kubectl apply -f deployment.yaml --validate=false
      - kubectl apply -f service.yaml --validate=false    
      - kubectl rollout restart -f deployment.yaml
      - kubectl get svc --all-namespaces
