apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: group1-eks-cluster
    app.kubernetes.io/instance: group1-eks-cluster-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: group1-eks-cluster
spec:
  selector:
    app: group1-eks-cluster
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000